# Generated by Django 4.2 on 2023-04-06 03:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('menu_name', models.CharField(max_length=50)),
                ('name_url', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Under_menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info_menu', models.TextField()),
                ('under_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.menu')),
            ],
        ),
    ]
