# Generated by Django 4.2 on 2023-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='under_menu',
            name='mini_menu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
